---

networks:
  vapiorc_network:
    driver: bridge

services:
  app:
    build: ./src
    container_name: vapiorc_app
    restart: unless-stopped
    working_dir: /src
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vapiorcdb
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/src
      - VAPIORC_HOST_BASE_DIR=${PWD}
      - VAPIORC_HOST_DATA_DIR=${PWD}/app_data
      - VAPIORC_CONTAINER_DATA_DIR=/app/data
      - VAPIORC_NETWORK=vapiorc_vapiorc_network
      - VAPIORC_PORT_START=8001
      - VAPIORC_PORT_END=8100
      - VAPIORC_HOT_SPARES=1
      - VAPIORC_HOST_IP=192.168.2.21
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - vapiorc_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw   # Docker socket for VM container management
      - ./app_data:/app/data                           # VM storage data
      - ./src/assets:/app/assets                       # Assets folder (install scripts, etc.)
      - /dev/kvm:/dev/kvm                              # KVM device passthrough for VM containers
    devices:
      - /dev/net/tun:/dev/net/tun                     # TUN device for VM networking
    cap_add:
      - NET_ADMIN                                     # Network administration capabilities
    privileged: true                                  # Required for Docker-in-Docker and KVM access

  db:
    image: postgres:15-alpine
    container_name: vapiorc_db
    restart: unless-stopped
    networks:
      - vapiorc_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # Change me!
      - POSTGRES_DB=vapiorcdb
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vapiorcdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: vapiorc_redis
    restart: unless-stopped
    networks:
      - vapiorc_network
    ports:
      - "6379:6379"
